language: ruby
rvm: 2.5.0
script:
- bundle exec rspec spec
before_install:
- openssl aes-256-cbc -K $encrypted_113a53810f46_key -iv $encrypted_113a53810f46_iv
  -in config/env.yml.enc -out config/env.yml -d
env:
  global:
    - CC_TEST_REPORTER_ID=cfd615f5c5b6cd83e1971160eed6d1ae1d3c79e71ab464addca3e8c1b4a154d6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
